// app/layout.tsx
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';


import type { Metadata } from "next";
import {Poppins} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from '@/components/Footer';

const font = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className} ${font.className} antialiased`}
      >
        {/* <TopHeader/> */}
        <main className="max-w-[1440px] mx-auto">
        <Navbar/>
        {children}
        <Footer/>
        </main>
      </body>
    </html>
  );
}
